version: "3.7"

services:
  spark-master:
    image: qiqi/spark:2.4.3
    command: spark-class org.apache.spark.deploy.master.Master
    container_name: spark-master
    hostname: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    networks:
      - spark-network
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_PUBLIC_DNS=localhost

  spark-worker-1:
    image: qiqi/spark:2.4.3
    command: spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - 8081:8081
    networks:
      - spark-network
    environment:
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_PUBLIC_DNS=localhost

  spark-worker-2:
    image: qiqi/spark:2.4.3
    command: spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - 8082:8082
    networks:
      - spark-network
    environment:
      - SPARK_WORKER_WEBUI_PORT=8082
      - SPARK_PUBLIC_DNS=localhost

networks:
  spark-network:
    name: spark-network